# Generated by Django 3.1.7 on 2021-08-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
