# Generated by Django 3.1.6 on 2021-04-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModelForm',
            new_name='ContactModel',
        ),
    ]
